# Generated by Django 2.2.1 on 2019-09-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_Id', models.CharField(max_length=100)),
                ('Car_name', models.CharField(max_length=100)),
                ('Car_type', models.CharField(max_length=100)),
                ('Rate_perday', models.CharField(max_length=100)),
                ('Photo', models.FileField(upload_to='media/')),
                ('img_url', models.CharField(max_length=100)),
            ],
        ),
    ]
