# Generated by Django 2.2.1 on 2019-11-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20191129_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='rentcar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Request_date', models.CharField(max_length=100)),
                ('Return_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='rentcars',
        ),
    ]
