# Generated by Django 2.2.1 on 2019-11-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20191129_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcar',
            name='Car_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rentcar',
            name='Request_date',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rentcar',
            name='Return_date',
            field=models.DateField(max_length=100),
        ),
    ]
